name: Inflate netkans
on:
    push:
        branches:
            - master
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
jobs:
    inflate:
        runs-on: ubuntu-latest
        container:
            image: ubuntu:latest
        steps:
            - name: Install a version of git that works (actions/checkout won't create a .git folder otherwise)
              run: apt-get update && apt-get install -y git
            - name: Get NetKAN repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Test modified netkans
              uses: HebaruSan/xKAN-meta_testing@github_action
              with:
                  source: commits
