name: Inflate netkans
on:
    push:
        branches:
            - master
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
jobs:
    Inflate:
        runs-on: ubuntu-latest
        steps:
            - name: Get NetKAN repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Cache downloads
              uses: actions/cache@v2
              with:
                  path: /cache
                  key: downloads-${{ github.run_id }}
                  restore-keys: |
                      downloads-
            - name: 'Check for comment containing #overwrite_cache'
              id: overwritecomment
              uses: khan/pull-request-comment-trigger@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  trigger: '#overwrite_cache'
                  reaction: rocket
            - name: Test modified netkans
              uses: HebaruSan/xKAN-meta_testing@github_action
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  source: commits
                  log level: debug
                  pull request body: ${{ github.event.pull_request.body }}
                  overwrite cache: ${{ steps.overwritecomment.outputs.triggered == 'true' }}
